name: library-site

type: "python:3.11"

mounts:
  "/static": "shared:files/static"
  "/media": "shared:files/media"
  "/logs": "shared:files/logs"

web:
  upstream:
    socket_family: unix
  commands:
    start: |
      gunicorn library_site.wsgi:application --bind unix:$SOCKET
  locations:
    "/":
      passthru: true
    "/static":
      root: "static"
      allow: true
      expires: 1h
    "/media":
      root: "media"
      allow: true
      expires: 1h

relationships:
  database: "db:postgresql"

variables:
  env:
    DJANGO_SETTINGS_MODULE: "library_site.settings"
    DEBUG: "False"
    ALLOWED_HOSTS: ".platform.sh"

disk: 512

hooks:
  build: |
    pip install --upgrade pip
    pip install -r requirements.txt
    pip install -r requirements_remote.txt
    mkdir -p static
    mkdir -p media
    mkdir logs
    python manage.py collectstatic --noinput
    rm -rf logs
  deploy: |
    python manage.py migrate
