# Generated by Django 5.2 on 2025-04-23 18:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_initial', models.CharField(blank=True, max_length=1)),
                ('last_name', models.CharField(max_length=30)),
                ('staff_id', models.PositiveIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_initial', models.CharField(blank=True, max_length=1)),
                ('last_name', models.CharField(max_length=30)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('year', models.CharField(max_length=20)),
                ('student_id', models.PositiveIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('publisher', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Enter a 4-digit year')])),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('zh', 'Chinese'), ('hi', 'Hindi'), ('ar', 'Arabic'), ('bn', 'Bengali'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('ja', 'Japanese'), ('de', 'German'), ('ko', 'Korean'), ('fr', 'French'), ('it', 'Italian'), ('tr', 'Turkish'), ('ta', 'Tamil'), ('vi', 'Vietnamese'), ('pl', 'Polish'), ('uk', 'Ukrainian'), ('ro', 'Romanian'), ('nl', 'Dutch')], max_length=2)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_borrowed', models.BooleanField(default=False)),
                ('borrowed_datetime', models.DateTimeField(blank=True, null=True)),
                ('to_be_returned', models.DateTimeField(blank=True, null=True)),
                ('returned_datetime', models.DateTimeField(blank=True, null=True)),
                ('borrowed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_books', to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
            options={
                'ordering': ['reserved_at'],
                'unique_together': {('student', 'book')},
            },
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_at', models.DateTimeField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
            options={
                'unique_together': {('student', 'book', 'borrowed_at')},
            },
        ),
    ]
