# Generated by Django 5.2 on 2025-04-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_librarian_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
