# Generated by Django 5.2 on 2025-04-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_librarian_user_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='returned_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
