# Generated by Django 5.2 on 2025-04-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_borrow_returned_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='returned_due_date',
            field=models.DateTimeField(),
        ),
    ]
