# Generated by Django 5.2 on 2025-04-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_borrow_returned_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, help_text='Upload a cover image (optional)', null=True, upload_to='covers/'),
        ),
    ]
